name: Pulumi Destroy

on:
  push:
    branches:
      - main
permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Required to read repository contents

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pulumi
        uses: pulumi/actions@v4
        with:
          command: version

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Select Pulumi Stack
        run: pulumi stack select dev

      - name: Destroy Pulumi Resources
        run: pulumi destroy --yes

      - name: Log Out of Pulumi
        run: pulumi logout
