name: Pulumi Destroy

on:
  workflow_dispatch:  # Allows manual execution
  pull_request:
    branches:
      - main  # Runs when a PR is opened against 'main'

permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Required to read repository contents

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install Pulumi CLI
      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
        with:
          pulumi-version: latest

      # Set up AWS credentials using OIDC
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
          role-session-name: GitHubActionsSession
      
      - name: Verify AWS Identity
        run: aws sts get-caller-identity
     
      # Set up Pulumi Access Token
      - name: Set up Pulumi Access Token
        run: |
          echo "PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_ACCESS_TOKEN }}" >> $GITHUB_ENV    

      # Install dependencies (if using Node.js)
      - name: Install dependencies
        run: npm install

      # Select the Pulumi stack
      - name: Select Pulumi Stack
        run: pulumi stack select dev

      # Destroy resources with Pulumi
      - name: Destroy Pulumi Resources
        run: pulumi destroy --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # Optional: Remove the stack after destroying resources
      - name: Remove Pulumi Stack (Optional)
        run: pulumi stack rm dev --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
