name: Pulumi Deployment

on:
  push:
    branches:
      - main
permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Required to read repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Pulumi CLI
        uses: pulumi/actions@v4
        with:
         pulumi-version: latest

      # Set up AWS credentials using OIDC
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          web-identity-token-file: ${{ secrets.AWS_WEB_IDENTITY_TOKEN_FILE }}
          aws-region: us-east-1
          role-session-name: GitHubActionsSession
      
      - name: Verify AWS Identity
        run: aws sts get-caller-identity
     
      - name: Set up Pulumi Access Token
        run: |
          echo "PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_ACCESS_TOKEN }}" >> $GITHUB_ENV    
     
      # Install dependencies (e.g., if using TypeScript, npm install)
      - name: Install dependencies
        run: npm install
      - name: Select Pulumi Stack
        run: pulumi stack select dev--non-interactive

      # Deploy with Pulumi
      - name: Deploy resources using Pulumi
        run: pulumi up --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
